################################################################################
#
# Makefile
# 
# Author: Jeff Shantz
#
# Targets:
#
#   asn4:  Build asn4 executable
#   clean: Remove all intermediary files
#   realclean: Remove intermediary and executable files
#
################################################################################

CC=gcc
MP=m4
CFLAGS=-c
LFLAGS=-o
DFLAGS=-g $(LFLAGS) 
OBJ_FILES=asn4.o myfadd.o stringio.o iofunc.o

asn4: $(OBJ_FILES) 
	$(CC) $(LFLAGS) asn4 $^

debug: $(OBJ_FILES) 
	$(CC) $(DFLAGS) asn4 $^

%.o: %.s
	$(CC) $(CFLAGS) $<

%.s: %.m
	-rm $@
	$(MP) $< > $@

realclean: clean
	-rm asn4

clean:
	-rm asn4.s myfadd.s
	-rm asn4.o myfadd.o stringio.o

